### ISSUE TITLE
Authorization server metadata value "issuer" is incorrect

### ISSUE THREAD

**Issue by Gadicuz** [ccpgames/sso-issues#61] opened 2020-02-03 10:57 UTC
# Bug

### Actual Behaviour

EVE SSO server metadata value "issuer" is "login.eveonline.com".

### Expected Behaviour

EVE SSO server metadata value "issuer" should be "https://login.eveonline.com".

### Description

EVE SSO server implements[ RFC 8414 OAuth 2.0 Authorization Server Metadata](https://tools.ietf.org/html/rfc8414) and provides metadata for an authorization server at a well-known location as a JSON document, which declares its endpoint locations and authorization server capabilities.

The JSON document is available at https://login.eveonline.com/.well-known/oauth-authorization-server or https://login.eveonline.com/.well-known/openid-configuration
```
{
   "issuer":"login.eveonline.com",
   "authorization_endpoint":"https://login.eveonline.com/v2/oauth/authorize",
   "token_endpoint":"https://login.eveonline.com/v2/oauth/token",
   "response_types_supported":["code","token"],
   "jwks_uri":"https://login.eveonline.com/oauth/jwks",
   "revocation_endpoint":"https://login.eveonline.com/v2/oauth/revoke",
   "revocation_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt"],
   "token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt"],
   "token_endpoint_auth_signing_alg_values_supported":["HS256"],
   "code_challenge_methods_supported":["S256"]
}
```

RFC 8414 Section 2 defines "issuer" value as a URL that uses the "https" scheme and has no query or fragment components.
RFC 8414 Section 3.3 requires the "issuer" value must be identical to the authorization server's issuer identifier value. If values are not identical, the data contained in the JSON document must not be used. EVE SSO authorization server's issuer identifier is "http://login.eveonline.com".

There are two problems with metadata value "issuer":
- it doesn't use "https" scheme (RFC 7230)
- it is not equal to EVE SSO authorization server's issuer identifier.

Standard processing EVE SSO authorization server's metadata JSON document results in ignoring metadata values due to "issuer" value validation failure.

**Comment by CarbonAlabel** [comment] 2020-02-17 00:16
Duplicate of https://github.com/ccpgames/sso-issues/issues/41

**Comment by HakShak** [comment] 2023-11-03 12:41
See https://github.com/ccpgames/sso-issues/issues/41#issuecomment-1792369921

**Closed as completed by HakShak** 2023-11-03 12:41 UTC
